name: Notify homebrew-chuck on release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to homebrew-chuck
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RELEASE_UPDATE_TOKEN }}
          repository: amperity/homebrew-chuck-data
          event-type: update-chuck-data-formula
          client-payload: |
            {
              "version": "${{ github.event.release.tag_name }}"
            }